/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "2.2.21"
}

allprojects {
    repositories {
        // Use jcenter for resolving dependencies.
        // You can declare any Maven/Ivy/file repository here.
        mavenCentral()
    }

    tasks.withType(JavaCompile::class).all {
        sourceCompatibility = "23"
        targetCompatibility = "23"
    }

    tasks.withType(KotlinCompile::class).all {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_23)
        }
    }

    tasks.withType(Test::class).configureEach {
        maxParallelForks = maxOf(Runtime.getRuntime().availableProcessors() / 2, 1)
        useJUnitPlatform()
    }

}
